In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [4]:
data = pd.read_csv('data_cleaned_2.csv')
data.head()

,Unnamed: 0,label,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_amt_ma,cnt_ma_rech30,fr_ma_rech30,sumamnt_ma_rech30,medianamnt_ma_rech30,medianmarechprebal30,cnt_ma_rech90,fr_ma_rech90,sumamnt_ma_rech90,medianamnt_ma_rech90,medianmarechprebal90,cnt_da_rech30,fr_da_rech30,cnt_da_rech90,fr_da_rech90,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,date,month
0,0,0,272.0,3055.050000,3065.150000,220.13,260.13,2.0,1539.0,2,21.0,3078.0,1539.0,7.50,2,21,3078.0,1539.0,7.50,0.0,0.0,0,0,2,12,6.0,0.0,2.0,12,6.0,0.0,9.375000,11.250000,20,7
1,1,1,712.0,12122.000000,12124.750000,3691.26,3691.26,16.0,4617.5,1,0.0,5787.0,3655.0,61.04,1,0,5787.0,3650.5,61.04,0.0,0.0,0,0,1,12,12.0,0.0,1.0,12,12.0,0.0,0.000000,0.000000,10,8
2,2,1,535.0,1398.000000,1398.000000,900.13,900.13,3.0,1539.0,1,0.0,1539.0,1539.0,66.32,1,0,1539.0,1539.0,66.32,0.0,0.0,0,0,1,6,6.0,0.0,1.0,6,6.0,0.0,0.000000,0.000000,19,8
3,3,1,241.0,21.228000,21.228000,159.42,159.42,16.0,947.0,0,0.0,0.0,0.0,0.00,1,0,947.0,947.0,2.50,0.0,0.0,0,0,2,12,6.0,0.0,2.0,12,6.0,0.0,0.000000,0.000000,6,6
4,4,1,947.0,150.619333,150.619333,1098.90,1098.90,4.0,2309.0,7,2.0,20029.0,2309.0,29.00,8,2,23496.0,2888.0,35.00,0.0,0.0,0,0,7,42,6.0,0.0,7.0,42,6.0,0.0,2.333333,2.333333,22,6

In [5]:
data.drop('Unnamed: 0',axis=1,inplace=True)
data.describe()

,label,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_amt_ma,cnt_ma_rech30,fr_ma_rech30,sumamnt_ma_rech30,medianamnt_ma_rech30,medianmarechprebal30,cnt_ma_rech90,fr_ma_rech90,sumamnt_ma_rech90,medianamnt_ma_rech90,medianmarechprebal90,cnt_da_rech30,fr_da_rech30,cnt_da_rech90,fr_da_rech90,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,date,month
count,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.00000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.00000,209593.000000
mean,0.875177,668.871098,4468.132828,4855.290617,2197.069184,2769.147968,4.977103,1719.109131,3.978057,4.065928,6861.071877,1475.941906,58.219786,6.31543,7.716780,10878.720344,1517.062192,55.956072,0.102775,0.122805,0.041495,0.045712,2.758981,17.952021,6.654554,0.054029,3.948896,23.645398,6.703134,0.046077,2.299777,2.894150,14.39894,6.797321
std,0.330519,513.525480,5859.376128,6438.197071,2552.708718,3251.352605,5.037840,1345.846661,4.256090,5.935577,6612.799020,1079.392998,64.544132,7.19347,12.590251,10789.012367,1056.056717,57.799928,1.155806,1.543246,0.397556,0.951386,2.554502,17.379741,2.147858,0.218039,5.402009,26.469861,2.103864,0.200692,3.030659,3.632511,8.43890,0.741435
min,0.000000,1.000000,0.000000,0.000000,-4334.360000,-5552.035000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-97.000000,0.00000,0.000000,0.000000,0.000000,-82.465000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,6.000000
25%,1.000000,246.000000,42.453000,42.693333,280.420000,300.260000,1.000000,770.000000,1.000000,0.000000,1540.000000,770.000000,11.000000,2.00000,0.000000,2317.000000,773.000000,14.600000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,6.000000,0.000000,1.000000,6.000000,6.000000,0.000000,0.000000,0.000000,7.00000,6.000000
50%,1.000000,527.000000,1469.175667,1500.000000,1083.570000,1334.000000,3.000000,1539.000000,3.000000,2.000000,4628.000000,1539.000000,33.900000,4.00000,2.000000,7226.000000,1539.000000,36.000000,0.000000,0.000000,0.000000,0.000000,2.000000,12.000000,6.000000,0.000000,2.000000,12.000000,6.000000,0.000000,0.000000,1.666667,14.00000,7.000000
75%,1.000000,982.000000,7244.000000,7802.790000,3356.940000,4201.790000,7.000000,2309.000000,5.000000,6.000000,10010.000000,1924.000000,83.000000,8.00000,8.000000,16000.000000,1924.000000,79.310000,0.000000,0.000000,0.000000,0.000000,4.000000,24.000000,6.000000,0.000000,5.000000,30.000000,6.000000,0.000000,3.750000,4.500000,21.00000,7.000000
max,1.000000,2086.000000,18046.320500,19442.935000,7971.720000,10054.085000,16.000000,4617.500000,203.000000,38.000000,22715.000000,3655.000000,191.000000,336.00000,88.000000,36524.500000,3650.500000,176.375000,16.000000,21.000000,38.000000,64.000000,50.000000,306.000000,12.000000,3.000000,55.000000,438.000000,12.000000,3.000000,9.375000,11.250000,31.00000,8.000000

Now we have seen in the visualisation that our data is rightly skewed, so I will be using log transformation so that it will normalise our data and also reduce the skewness

In [13]:
for i in data:
    print(i)
    print('skewness of data before transformation :', data[i].skew())
    print('skewness of data after transformation :', np.log1p(data[i]+1).skew())
    print('\n')

label
skewness of data before transformation : -2.270253719912255
skewness of data after transformation : -2.2702537199122483


aon
skewness of data before transformation : 0.9523735650957931
skewness of data after transformation : -0.5522029813963728


daily_decr30
skewness of data before transformation : 1.2392378160520385
skewness of data after transformation : -0.41935115858549166


daily_decr90
skewness of data before transformation : 1.2390013758145795
skewness of data after transformation : -0.4051138844896607


rental30
skewness of data before transformation : 1.1925098502039457
skewness of data after transformation : -1.2425810928362262


rental90
skewness of data before transformation : 1.193291113119697
skewness of data after transformation : -1.2088782173635169


last_rech_date_ma
skewness of data before transformation : 1.1339579204137522
skewness of data after transformation : 0.3365113184640076


last_rech_amt_ma
skewness of data before transformation : 1.0034464262823297
skewness of data after transformation : -2.2539554499341623


cnt_ma_rech30
skewness of data before transformation : 3.283841502993646
skewness of data after transformation : 0.348146038619659


fr_ma_rech30
skewness of data before transformation : 2.4087247582252584
skewness of data after transformation : 0.6622394255841083


sumamnt_ma_rech30
skewness of data before transformation : 1.0807706400852082
skewness of data after transformation : -1.7468050504692918


medianamnt_ma_rech30
skewness of data before transformation : 0.7282185308830263
skewness of data after transformation : -1.9332918992412005


medianmarechprebal30
skewness of data before transformation : 0.9886279675189577
skewness of data after transformation : nan


cnt_ma_rech90
skewness of data before transformation : 3.4252536465582106
skewness of data after transformation : 0.2912021704344597


fr_ma_rech90
skewness of data before transformation : 2.285422796522632
skewness of data after transformation : 0.7703781004567621


sumamnt_ma_rech90
skewness of data before transformation : 1.1264207157552313
skewness of data after transformation : -1.9984046265673545


medianamnt_ma_rech90
skewness of data before transformation : 0.7639035559681836
skewness of data after transformation : -2.329504709826757


medianmarechprebal90
skewness of data before transformation : 0.9579331134878262
skewness of data after transformation : nan


cnt_da_rech30
skewness of data before transformation : 13.257074159850495
skewness of data after transformation : 11.377206740167793


fr_da_rech30
skewness of data before transformation : 13.064455366524529
skewness of data after transformation : 12.326652516101655


cnt_da_rech90
skewness of data before transformation : 27.267277681861458
skewness of data after transformation : 10.084967909947071


fr_da_rech90
skewness of data before transformation : 28.98808270697841
skewness of data after transformation : 18.965303653996006


cnt_loans30
skewness of data before transformation : 2.713421086900181
skewness of data after transformation : 0.9791642507869208


amnt_loans30
skewness of data before transformation : 2.9757194730831107
skewness of data after transformation : 0.29545930721841096


maxamnt_loans30
skewness of data before transformation : 1.4355872150244522
skewness of data after transformation : -1.7015956085806996


medianamnt_loans30
skewness of data before transformation : 4.551043016959967
skewness of data after transformation : 4.154672455594125


cnt_loans90
skewness of data before transformation : 5.354680055239517
skewness of data after transformation : 1.2261474207831287


amnt_loans90
skewness of data before transformation : 3.150006331942554
skewness of data after transformation : 0.4448647266809498


maxamnt_loans90
skewness of data before transformation : 1.6783037897368753
skewness of data after transformation : -1.0365942028967534


medianamnt_loans90
skewness of data before transformation : 4.895720276504792
skewness of data after transformation : 4.499881007255553


payback30
skewness of data before transformation : 1.1893120356391396
skewness of data after transformation : 0.6006751633335681


payback90
skewness of data before transformation : 1.170814527217898
skewness of data after transformation : 0.4823116093999208


date
skewness of data before transformation : 0.19984532530201307
skewness of data after transformation : -0.722934346170896


month
skewness of data before transformation : 0.3432418941187077
skewness of data after transformation : 0.2514369397476161

There are some columns which are negatively affected by log transformation, so I will be transforming selected columns only

In [14]:
data['aon'] = np.log1p(data['aon']+1)
data['daily_decr30'] = np.log1p(data['daily_decr30']+1)
data['daily_decr90'] = np.log1p(data['daily_decr90']+1)
data['last_rech_date_ma'] = np.log1p(data['last_rech_date_ma']+1)
data['cnt_ma_rech30'] = np.log1p(data['cnt_ma_rech30']+1)
data['fr_ma_rech30'] = np.log1p(data['fr_ma_rech30']+1)
data['cnt_ma_rech90'] = np.log1p(data['cnt_ma_rech90']+1)
data['fr_ma_rech90'] = np.log1p(data['fr_ma_rech90']+1)
data['cnt_loans30'] = np.log1p(data['cnt_loans30']+1)
data['amnt_loans30'] = np.log1p(data['amnt_loans30']+1)
data['cnt_loans90'] = np.log1p(data['cnt_loans90']+1)
data['amnt_loans90'] = np.log1p(data['amnt_loans90']+1)
data['payback30'] = np.log1p(data['payback30']+1)
data['payback90'] = np.log1p(data['payback90']+1)

In [15]:
data.skew()

label                   -2.270254
aon                     -0.552203
daily_decr30            -0.419351
daily_decr90            -0.405114
rental30                 1.192510
rental90                 1.193291
last_rech_date_ma        0.336511
last_rech_amt_ma         1.003446
cnt_ma_rech30            0.348146
fr_ma_rech30             0.662239
sumamnt_ma_rech30        1.080771
medianamnt_ma_rech30     0.728219
medianmarechprebal30     0.988628
cnt_ma_rech90            0.291202
fr_ma_rech90             0.770378
sumamnt_ma_rech90        1.126421
medianamnt_ma_rech90     0.763904
medianmarechprebal90     0.957933
cnt_da_rech30           13.257074
fr_da_rech30            13.064455
cnt_da_rech90           27.267278
fr_da_rech90            28.988083
cnt_loans30              0.979164
amnt_loans30             0.295459
maxamnt_loans30          1.435587
medianamnt_loans30       4.551043
cnt_loans90              1.226147
amnt_loans90             0.444865
maxamnt_loans90          1.678304
medianamnt_loans90       4.895720
payback30                0.600675
payback90                0.482312
date                     0.199845
month                    0.343242
dtype: float64

In [20]:
data.to_csv('log_transformed.csv')